// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Settings {
	
	
	public partial class FrontendLangEdit {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.DropDownList LanguageList;
		
		protected System.Web.UI.WebControls.CustomValidator LanguageDuplicateValidator;
		
		protected System.Web.UI.WebControls.TextBox DisplayName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator DisplayNameRequiredValidator;
		
		protected System.Web.UI.WebControls.TextBox Domain;
		
		protected System.Web.UI.WebControls.LinkButton SubmitButton;
	}
}
