// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Settings {
	
	
	public partial class SiteInfoEdit {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.PlaceHolder LanguageHodler;
		
		protected System.Web.UI.WebControls.DropDownList LanguageList;
		
		protected System.Web.UI.WebControls.TextBox SiteTitle;
		
		protected System.Web.UI.WebControls.TextBox SiteSubtitle;
		
		protected System.Web.UI.WebControls.PlaceHolder LogoPreviewHolder;
		
		protected System.Web.UI.WebControls.Image LogoPreview;
		
		protected System.Web.UI.WebControls.CheckBox DeleteLogo;
		
		protected System.Web.UI.WebControls.FileUpload LogoUpload;
		
		protected System.Web.UI.WebControls.CustomValidator LogoValidator;
		
		protected System.Web.UI.WebControls.TextBox Copyright;
		
		protected System.Web.UI.WebControls.TextBox MiiBeiAnNumber;
		
		protected System.Web.UI.WebControls.TextBox PageTitle;
		
		protected System.Web.UI.WebControls.TextBox PageMetaKeywords;
		
		protected System.Web.UI.WebControls.TextBox PageMetaDescription;
		
		protected System.Web.UI.WebControls.LinkButton SubmitButton;
	}
}
