// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Settings {
	
	
	public partial class SmtpSettingsEdit {
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.TextBox SmtpServer;
		
		protected System.Web.UI.WebControls.TextBox Port;
		
		protected System.Web.UI.WebControls.CheckBox EnableSsl;
		
		protected System.Web.UI.WebControls.TextBox SenderName;
		
		protected System.Web.UI.WebControls.TextBox SenderEmail;
		
		protected System.Web.UI.WebControls.TextBox AccountName;
		
		protected System.Web.UI.WebControls.TextBox AccountPassword;
		
		protected System.Web.UI.WebControls.Button SaveButton;
	}
}
