// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Urls {
	
	
	public partial class CustomRedirectEdit {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.DropDownList RedirectMode;
		
		protected System.Web.UI.WebControls.TextBox From;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator FromRequiredValidator;
		
		protected System.Web.UI.WebControls.TextBox To;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator ToRequiredValidator;
		
		protected System.Web.UI.WebControls.CheckBox MatchByRegex;
		
		protected System.Web.UI.WebControls.TextBox Priority;
		
		protected System.Web.UI.WebControls.CheckBox IsEnabled;
		
		protected System.Web.UI.WebControls.LinkButton SubmitButton;
	}
}
