// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Designer.Controls {
	
	
	public partial class AllWidgets {
		
		protected System.Web.UI.WebControls.Repeater CategoryRepeater;
		
		protected System.Web.UI.WebControls.Repeater CategoryWidgetsRepeater;
		
		protected Seeger.Web.UI.Admin.Designer.Controls.WidgetList WidgetList;
	}
}
