// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Plugins.Analytics.Admin {
	
	
	public partial class Analytics {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox Code;
		
		protected System.Web.UI.WebControls.CheckBox EnableAnalyticsCode;
		
		protected System.Web.UI.WebControls.LinkButton SaveButton;
	}
}
