// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Templates.Default.Layouts.TwoColumn1 {
	
	
	public partial class Default {
		
		protected Seeger.Web.UI.ZoneControl BannerZone1;
		
		protected Seeger.Web.UI.ZoneControl SideZone1;
		
		protected Seeger.Web.UI.ZoneControl MainZone;
		
		protected Seeger.Web.UI.ZoneControl BannerZone2;
	}
}
