//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeger.Web.UI.Templates.Default.Layouts.TwoColumn1 {
    
    
    public partial class Designer {
        
        /// <summary>
        /// BannerZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.ZoneControl BannerZone1;
        
        /// <summary>
        /// SideZone1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.ZoneControl SideZone1;
        
        /// <summary>
        /// MainZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.ZoneControl MainZone;
        
        /// <summary>
        /// BannerZone2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.ZoneControl BannerZone2;
    }
}
