tinyMCE.addI18n('zh-CN.advanced',{
style_select:"Styles",
font_size:"字体大小",
fontdefault:"字体",
block:"格式",
paragraph:"段落",
div:"Div",
address:"地址",
pre:"Preformatted",
h1:"标题 1",
h2:"标题 2",
h3:"标题 3",
h4:"标题 4",
h5:"标题 5",
h6:"标题 6",
blockquote:"Blockquote",
code:"Code",
samp:"Code sample",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"加粗 (Ctrl+B)",
italic_desc:"斜体 (Ctrl+I)",
underline_desc:"下划线 (Ctrl+U)",
striketrough_desc:"删除线",
justifyleft_desc:"左对齐",
justifycenter_desc:"居中对齐",
justifyright_desc:"右对齐",
justifyfull_desc:"两边对齐",
bullist_desc:"无序列表",
numlist_desc:"有序列表",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"撤消 (Ctrl+Z)",
redo_desc:"重做 (Ctrl+Y)",
link_desc:"插入/编辑链接",
unlink_desc:"取消链接",
image_desc:"插入/编辑图片",
cleanup_desc:"清洁代码",
code_desc:"源代码",
sub_desc:"下标",
sup_desc:"上标",
hr_desc:"插入水平线",
removeformat_desc:"清除样式",
custom1_desc:"Your custom description here",
forecolor_desc:"文字颜色",
backcolor_desc:"背景颜色",
charmap_desc:"插入特殊字符",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"剪切",
copy_desc:"复制",
paste_desc:"粘贴",
image_props_desc:"图片属性",
newdocument_desc:"New document",
help_desc:"帮助",
blockquote_desc:"Blockquote",
clipboard_msg:"Copy/Cut/Paste is not available in Mozilla and Firefox.\r\nDo you want more information about this issue?",
path:"路径",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"更多颜色"
});