tinyMCE.addI18n('zh-CN.advanced_dlg',{
about_title:"About TinyMCE",
about_general:"About",
about_help:"Help",
about_license:"License",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Author",
about_version:"Version",
about_loaded:"Loaded plugins",
anchor_title:"Insert/edit anchor",
anchor_name:"Anchor name",
code_title:"源代码编辑器",
code_wordwrap:"自动换行",
colorpicker_title:"选择颜色",
colorpicker_picker_tab:"选择器",
colorpicker_picker_title:"颜色选择器",
colorpicker_palette_tab:"调色板",
colorpicker_palette_title:"调色板颜色",
colorpicker_named_tab:"命名颜色",
colorpicker_named_title:"命名颜色",
colorpicker_color:"颜色:",
colorpicker_name:"名称:",
charmap_title:"选择特殊字符",
image_title:"插入/编辑图片",
image_src:"图片地址",
image_alt:"图片描述",
image_list:"图片列表",
image_border:"边框",
image_dimensions:"尺寸",
image_vspace:"垂直空白",
image_hspace:"水平空白",
image_align:"对齐",
image_align_baseline:"基线对齐",
image_align_top:"顶部对齐",
image_align_middle:"居中对齐",
image_align_bottom:"底部对齐",
image_align_texttop:"文本顶部对齐",
image_align_textbottom:"文本底部对齐",
image_align_left:"左对齐",
image_align_right:"右对齐",
link_title:"插入/编辑链接",
link_url:"链接地址",
link_target:"目标",
link_target_same:"在当前窗口中打开",
link_target_blank:"在新窗口中打开",
link_titlefield:"标题",
link_is_email:"您输入的地址是Email地址, 需要添加'mailto'前缀吗?",
link_is_external:"您输入的地址是外部链接, 需要添加'http://'前缀吗?",
link_list:"链接列表"
});