// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Plugins {
	
	
	public partial class PluginList {
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.Repeater List;
		
		protected System.Web.UI.WebControls.PlaceHolder InstallHolder;
		
		protected System.Web.UI.WebControls.PlaceHolder UninstallHolder;
		
		protected System.Web.UI.WebControls.PlaceHolder EnableHolder;
		
		protected System.Web.UI.WebControls.PlaceHolder DisableHolder;
	}
}
