// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Security {
	
	
	public partial class PrivilegeView {
		
		protected System.Web.UI.WebControls.Repeater FunctionRepeater;
		
		protected System.Web.UI.WebControls.CheckBoxList Operations;
	}
}
