// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Security {
	
	
	public partial class RoleEdit {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox Name;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator NameRequiredValidator;
		
		protected Seeger.Web.UI.Admin.Security.PrivilegeView Privileges;
		
		protected System.Web.UI.WebControls.LinkButton SubmitButton;
	}
}
