// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Security {
	
	
	public partial class UserEdit {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox UserName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator UserNameRequired;
		
		protected System.Web.UI.WebControls.CustomValidator UserNameDuplicateValidator;
		
		protected System.Web.UI.WebControls.TextBox Nick;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
		
		protected System.Web.UI.WebControls.CheckBoxList RoleList;
		
		protected System.Web.UI.WebControls.LinkButton SubmitButton;
	}
}
