// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.My {
	
	
	public partial class Profile {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Literal UserName;
		
		protected System.Web.UI.WebControls.TextBox Nick;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator EmailRequiredValidator;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.TextBox PasswordConfirm;
		
		protected System.Web.UI.WebControls.CompareValidator PasswordConfirmValidator;
		
		protected System.Web.UI.WebControls.DropDownList SkinList;
		
		protected System.Web.UI.WebControls.DropDownList LanguageList;
		
		protected System.Web.UI.WebControls.LinkButton SubmitButton;
	}
}
