// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Shared {
	
	
	public partial class Popup {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder HeadHolder;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Literal Message;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainHolder;
	}
}
