// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Plugins.AppKeepAlive.Admin {
	
	
	public partial class Settings {
		
		protected System.Web.UI.WebControls.Content Content3;
		
		protected System.Web.UI.WebControls.TextBox Url;
		
		protected System.Web.UI.WebControls.TextBox Interval;
		
		protected System.Web.UI.WebControls.Button SaveButton;
	}
}
