// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Licensing {
	
	
	public partial class LicenseInfo {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected Seeger.Web.UI.Admin.Licensing.InvalidLicenseHint InvalidLicenseHint;
		
		protected Seeger.Web.UI.Admin.Licensing.CurrentDomainHint CurrentDomainHint;
		
		protected Seeger.Web.UI.Admin.Licensing.DomainBindingHint DomainBindingHint;
		
		protected System.Web.UI.WebControls.PlaceHolder LicenseInfoHolder;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
