//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Licensing {
    
    
    public partial class LicenseInfo {
        
        /// <summary>
        /// InvalidLicenseHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Licensing.InvalidLicenseHint InvalidLicenseHint;
        
        /// <summary>
        /// CurrentDomainHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Licensing.CurrentDomainHint CurrentDomainHint;
        
        /// <summary>
        /// DomainBindingHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Licensing.DomainBindingHint DomainBindingHint;
        
        /// <summary>
        /// LicenseInfoHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder LicenseInfoHolder;
    }
}
