// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Templates.Default.Layouts {
	
	
	public partial class Front {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Literal Logo;
		
		protected System.Web.UI.WebControls.Literal Subtitle;
		
		protected System.Web.UI.WebControls.Literal Menu;
		
		protected System.Web.UI.WebControls.Literal LanguageSwitch;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainHodler;
		
		protected System.Web.UI.WebControls.Literal Copyright;
		
		protected System.Web.UI.WebControls.Literal PoweredBy;
		
		protected System.Web.UI.WebControls.Literal MiiBeiAnNumber;
		
		protected System.Web.UI.WebControls.PlaceHolder AnalyticsCodeHolder;
	}
}
