// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Pages {
	
	
	public partial class PageEdit {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.PlaceHolder ParentPageHolder;
		
		protected System.Web.UI.WebControls.Literal ParentPageName;
		
		protected System.Web.UI.WebControls.TextBox Name;
		
		protected System.Web.UI.WebControls.PlaceHolder VisibleInMenuHolder;
		
		protected System.Web.UI.WebControls.CheckBox VisibleInMenu;
		
		protected System.Web.UI.WebControls.TextBox PageUniqueName;
		
		protected System.Web.UI.WebControls.CheckBox Deletable;
		
		protected System.Web.UI.WebControls.Literal BaseUrl;
		
		protected System.Web.UI.WebControls.TextBox UrlSegment;
		
		protected System.Web.UI.WebControls.CustomValidator UrlSegmentDuplicateValidator;
		
		protected System.Web.UI.WebControls.TextBox BindedDomains;
		
		protected System.Web.UI.WebControls.DropDownList TemplateList;
		
		protected System.Web.UI.WebControls.Repeater TemplateLayoutList;
		
		protected System.Web.UI.WebControls.Repeater LayoutList;
		
		protected System.Web.UI.WebControls.TextBox CurrentLayout;
		
		protected System.Web.UI.WebControls.Repeater TemplateSkinList;
		
		protected System.Web.UI.WebControls.Repeater SkinList;
		
		protected System.Web.UI.WebControls.TextBox CurrentSkin;
		
		protected System.Web.UI.WebControls.CheckBox Published;
		
		protected System.Web.UI.WebControls.LinkButton SaveButton;
	}
}
