// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Pages {
	
	
	public partial class PageSEO {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.PlaceHolder LanguageHolder;
		
		protected System.Web.UI.WebControls.Literal LanguageName;
		
		protected System.Web.UI.WebControls.TextBox PageTitle;
		
		protected System.Web.UI.WebControls.TextBox PageMetaKeywords;
		
		protected System.Web.UI.WebControls.TextBox PageMetaDescription;
		
		protected System.Web.UI.WebControls.LinkButton SaveButton;
	}
}
