// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin.Designer {
	
	
	public partial class Toolbox {
		
		protected Seeger.Web.UI.Admin.Designer.Controls.AllWidgets AllWidgets;
		
		protected System.Web.UI.WebControls.PlaceHolder SelectLanguageHolder;
		
		protected System.Web.UI.WebControls.DropDownList CultureList;
	}
}
