//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeger.Web.UI.Admin {
    
    
    public partial class Dashboard {
        
        /// <summary>
        /// InvalidLicenseHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Licensing.InvalidLicenseHint InvalidLicenseHint;
        
        /// <summary>
        /// CurrentDomainHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Licensing.CurrentDomainHint CurrentDomainHint;
        
        /// <summary>
        /// DomainBindingHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Licensing.DomainBindingHint DomainBindingHint;
        
        /// <summary>
        /// UpgradeBrowserHint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Controls.UpgradeBrowserHint UpgradeBrowserHint;
        
        /// <summary>
        /// UpdateCheck control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Controls.UpdateCheck UpdateCheck;
        
        /// <summary>
        /// SeegerNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Seeger.Web.UI.Admin.Controls.SeegerNews SeegerNews;
    }
}
